### ISSUE TITLE
Conflict with matplotlib 3.9.0 version after installation via PyPi

### ISSUE THREAD

**Issue by ArtemLiA** [etna-team/etna#379] opened 2024-06-03 15:54 UTC
### 🐛 Bug Report

When trying to import `Pipeline` after installing all etna extensions by running `!pip install etna[all]`, the following error occurs:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 1
----> 1 from etna.pipeline import Pipeline

File ~\DevTools\AnacondaTool\envs\etna-dev\lib\site-packages\etna\pipeline\__init__.py:3
      1 """Module with pipelines for time-series forecasting."""
----> 3 from etna.pipeline.assembling_pipelines import assemble_pipelines
      4 from etna.pipeline.autoregressive_pipeline import AutoRegressivePipeline
      5 from etna.pipeline.base import BasePipeline

File ~\DevTools\AnacondaTool\envs\etna-dev\lib\site-packages\etna\pipeline\assembling_pipelines.py:9
      6 from typing import Union
      8 from etna.models.base import ModelType
----> 9 from etna.pipeline.pipeline import Pipeline
     10 from etna.transforms import Transform
     13 def assemble_pipelines(
     14     models: Union[ModelType, Sequence[ModelType]],
     15     transforms: Sequence[Union[Transform, Sequence[Optional[Transform]]]],
     16     horizons: Union[int, Sequence[int]],
     17 ) -> List[Pipeline]:

File ~\DevTools\AnacondaTool\envs\etna-dev\lib\site-packages\etna\pipeline\pipeline.py:14
     12 from etna.models.base import PredictionIntervalContextRequiredAbstractModel
     13 from etna.pipeline.base import BasePipeline
---> 14 from etna.pipeline.mixins import ModelPipelineParamsToTuneMixin
     15 from etna.pipeline.mixins import ModelPipelinePredictMixin
     16 from etna.pipeline.mixins import SaveModelPipelineMixin

File ~\DevTools\AnacondaTool\envs\etna-dev\lib\site-packages\etna\pipeline\mixins.py:25
     23 from etna.models import PredictionIntervalContextIgnorantAbstractModel
     24 from etna.models import PredictionIntervalContextRequiredAbstractModel
---> 25 from etna.transforms import Transform
     28 class ModelPipelinePredictMixin:
     29     """Mixin for pipelines with model inside with implementation of ``_predict`` method."""

File ~\DevTools\AnacondaTool\envs\etna-dev\lib\site-packages\etna\transforms\__init__.py:25
     23 from etna.transforms.encoders import OneHotEncoderTransform
     24 from etna.transforms.encoders import SegmentEncoderTransform
---> 25 from etna.transforms.feature_selection import FilterFeaturesTransform
     26 from etna.transforms.feature_selection import GaleShapleyFeatureSelectionTransform
     27 from etna.transforms.feature_selection import MRMRFeatureSelectionTransform

File ~\DevTools\AnacondaTool\envs\etna-dev\lib\site-packages\etna\transforms\feature_selection\__init__.py:2
      1 from etna.transforms.feature_selection.base import BaseFeatureSelectionTransform
----> 2 from etna.transforms.feature_selection.feature_importance import MRMRFeatureSelectionTransform
      3 from etna.transforms.feature_selection.feature_importance import TreeFeatureSelectionTransform
      4 from etna.transforms.feature_selection.filter import FilterFeaturesTransform

File ~\DevTools\AnacondaTool\envs\etna-dev\lib\site-packages\etna\transforms\feature_selection\feature_importance.py:17
     14 from sklearn.tree import ExtraTreeRegressor
     15 from typing_extensions import Literal
---> 17 from etna.analysis import RelevanceTable
     18 from etna.analysis.feature_selection.mrmr_selection import AggregationMode
     19 from etna.analysis.feature_selection.mrmr_selection import mrmr

File ~\DevTools\AnacondaTool\envs\etna-dev\lib\site-packages\etna\analysis\__init__.py:10
      8 from etna.analysis.decomposition import seasonal_plot
      9 from etna.analysis.decomposition import stl_plot
---> 10 from etna.analysis.eda import acf_plot
     11 from etna.analysis.eda import cross_corr_plot
     12 from etna.analysis.eda import distribution_plot

File ~\DevTools\AnacondaTool\envs\etna-dev\lib\site-packages\etna\analysis\eda\__init__.py:1
----> 1 from etna.analysis.eda.plots import acf_plot
      2 from etna.analysis.eda.plots import cross_corr_plot
      3 from etna.analysis.eda.plots import distribution_plot

File ~\DevTools\AnacondaTool\envs\etna-dev\lib\site-packages\etna\analysis\eda\plots.py:17
     15 import numpy as np
     16 import pandas as pd
---> 17 import seaborn as sns
     18 import statsmodels.api as sm
     19 from matplotlib.lines import Line2D

File ~\DevTools\AnacondaTool\envs\etna-dev\lib\site-packages\seaborn\__init__.py:9
      7 from .categorical import *  # noqa: F401,F403
      8 from .distributions import *  # noqa: F401,F403
----> 9 from .matrix import *  # noqa: F401,F403
     10 from .miscplot import *  # noqa: F401,F403
     11 from .axisgrid import *  # noqa: F401,F403

File ~\DevTools\AnacondaTool\envs\etna-dev\lib\site-packages\seaborn\matrix.py:12
      9 import pandas as pd
     10 from scipy.cluster import hierarchy
---> 12 from . import cm
     13 from .axisgrid import Grid
     14 from .utils import (
     15     despine,
     16     axis_ticklabels_overlap,
   (...)
     19     _draw_figure,
     20 )

File ~\DevTools\AnacondaTool\envs\etna-dev\lib\site-packages\seaborn\cm.py:1582
   1579     _cmap_r = colors.ListedColormap(_lut[::-1], _name + "_r")  
   1580     locals()[_name + "_r"] = _cmap_r
-> 1582     mpl_cm.register_cmap(_name, _cmap)
   1583     mpl_cm.register_cmap(_name + "_r", _cmap_r)
   1585 del colors, mpl_cm

AttributeError: module 'matplotlib.cm' has no attribute 'register_cmap'
```
I can assume that this error is caused due to the installation of an incorrect version of *matplotlib*. When installing *etna* dependencies, *matplotlib 3.9.0* was installed (before that, matplotlib was not installed and was installed with dependencies) and after downgrade *matplotlib* to version 3.7 using
```
!pip install --force-reinstall matplotlib==3.7
```
the error disappears and `Pipeline` is correctly imported.

### Expected behavior

No errors and correct import.

### How To Reproduce

1. Create new environment with `python 3.9.16`
2. Install all the etna extensions using PyPi by running `!pip install etna[all]`
3. Run `from etna.pipeline import Pipeline`

### Environment

python: 3.9.16

### Checklist

- [X] Bug appears at the latest library version

**Comment by d-a-bunin** [comment] 2024-06-03 17:10
It is a duplicate of #318.

It is already fixed in `master` branch. The fix will be released in v2.7.0. The temporary fix it to install more modern version of seaborn.

**Closed by d-a-bunin** 2024-06-03 17:10 UTC
Labels: bug
